# Generated by Django 4.0.6 on 2022-08-13 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='value',
            field=models.CharField(max_length=1),
        ),
    ]
